export const AppState = {
    invoke: null,
    scripts: [],
    templates: [],
    settings: null,
    compressionPreview: null,
    isCompressing: false,
    selectedScript: null,
    selectedTemplate: null,
    compositionTemplateId: null,
    compositionDraftTemplate: null,
    workspaceMode: 'browse',
    compositionScripts: [],
    currentTemplateId: null,
    editMode: 'view',
    originalScriptData: null,
    variableValues: {},
    templateEditorOriginalData: null,
    scriptFavoritesOnly: false,
    templateFavoritesOnly: false,
};
